name: Deploy Docs

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build and lint project
        uses: leanprover/lean-action@v1

      - name: Build and deploy documentation
        uses: leanprover-community/docgen-action@main
